@isTest
public with sharing class WarehouseCalloutServiceTest {
    @isTest static void demoMethod(){
    Test.startTest();
    // Integer a = WarehouseCalloutService.babyMethod(5,6);
    Test.stopTest();

    // System.assertEquals(11,a);


        // Test.setMock(HttpCalloutMock.class, new WarehouseCalloutServiceMock());

        // Test.startTest();
        
        // System.enqueueJob(new WarehouseCalloutService());
        // Test.stopTest();


        // String contentType = response.getHeader('Content-Type');
        // System.assert(contentType == 'application/json');
        // String expectedValue='{"_id":"55d66226726b611100aaf741","replacement":false,"quantity":5,"name":"Generator 1000 kW","maintenanceperiod":365,"lifespan":120,"cost":5000,"sku":"100003"}';
        // String actualValue = response.getBody();
        // System.assertEquals(expectedValue, actualValue);

    }
}